name: stockfish
description: The Stockfish Chess Engine for Flutter.
version: 1.7.2
repository: https://github.com/ArjanAswal/stockfish.git
homepage: https://github.com/ArjanAswal/stockfish.git
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'
dependencies:
  ffi: ^2.0.0
  flutter:
    sdk: flutter
  logging: ^1.2.0
  hooks: ^1.0.0
  code_assets: ^1.0.0
  native_toolchain_c: ^0.17.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      windows:
        ffiPlugin: true
  assets:
    - macos/src/stockfish/nnue/nn-1111cefa1111.nnue
    - macos/src/stockfish/nn-37f18f62d772.nnue